#NAME: Mudith Mallajosyula
#EMAIL: mudithm@g.ucla.edu
#ID: 404937201

TARFILES=Makefile README my_beaglebone.jpg connected.png copy.png build_run.png git.png


dist: $(TARFILES)
	tar -cvzf lab4a-404937201.tar.gz $(TARFILES)

clean:
	rm -f *.tar.gz
