#NAME: Mudith Mallajosyula
#EMAIL: mudithm@g.ucla.edu
#ID: 404937201

CC=gcc
CFLAGS=-Wall -Wextra -pthread
TARFILES=lab2_add.c SortedList.h SortedList.c lab2_list.c Makeifle lab2_add.csv lab2_list.csv README
GRAPHS=lab2_add-1.png lab2_add-2.png lab2_add-3.png lab2_add-4.png lab2_add-5.png lab2_list-1.png lab2_list-2.png lab2_list-3.png lab2_list-4.png

build: lab2_add.c lab2_list.c
	$(CC) lab2_add.c $(CFLAGS) -o lab2_add
	$(CC) lab2_list.c $(CFLAGS) -o lab2_list

tests:


graphs:


dist:


clean:
